<wsdl:definitions
     name="ReceiveLOEmail"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ums/LoanOriginationProcess/LoanOrigination/ReceiveLOEmail"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ums/LoanOriginationProcess/LoanOrigination/ReceiveLOEmail"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://platform.integration.oracle/blocks/adapter/fw/metadata/ReceiveLOEmail"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ReceiveLONotification_plt" >
    <plt:role name="ReceiveLONotification_role" >
      <plt:portType name="tns:ReceiveLONotification_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://platform.integration.oracle/blocks/adapter/fw/metadata/ReceiveLOEmail" schemaLocation="../Schemas/ReceiveLOEmail.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ReceiveLONotification_msg">
        <wsdl:part name="body" element="imp1:message"/>
    </wsdl:message>
    <wsdl:portType name="ReceiveLONotification_ptt">
        <wsdl:operation name="ReceiveLONotification">
            <wsdl:input message="tns:ReceiveLONotification_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
