<wsdl:definitions
     name="PushToFeedbackQueue"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/LoanOriginationApp/LoanOriginationProject/PushToFeedbackQueue"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/LoanOriginationApp/LoanOriginationProject/PushToFeedbackQueue"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://www.samplebank.org"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Produce_Message_plt" >
    <plt:role name="Produce_Message_role" >
      <plt:portType name="tns:Produce_Message_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://www.samplebank.org" schemaLocation="xsd/LoanOrig.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Produce_Message_msg">
        <wsdl:part name="body" element="imp1:LoanRequest"/>
    </wsdl:message>
    <wsdl:portType name="Produce_Message_ptt">
        <wsdl:operation name="Produce_Message">
            <wsdl:input message="tns:Produce_Message_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
